# Copyright (c) 2022, 2023 Humanitarian OpenStreetMap Team
# This file is part of FMTM.
#
#     FMTM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     FMTM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with FMTM.  If not, see <https:#www.gnu.org/licenses/>.
#

version: "3"

volumes:
  fmtm_frontend:
    name: fmtm-frontend-main
  fmtm_db_data:
    name: fmtm-db-data-main
  fmtm_logs:
    name: fmtm-logs-main
  fmtm_images:
    name: fmtm-images-main
  fmtm_tiles:
    name: fmtm-tiles-main
  certs:
    name: fmtm-certs-main
  certbot_data:
    name: fmtm-certbot-data-main

networks:
  fmtm-net:
    name: fmtm-main

services:
  proxy:
    image: "ghcr.io/hotosm/fmtm/proxy:main${FMTM_SCRIPT_DOMAIN:+-plus-script}"
    container_name: fmtm-main
    depends_on:
      api:
        condition: service_started
      certbot:
        condition: service_completed_successfully
      ui:
        condition: service_completed_successfully
    volumes:
      - fmtm_frontend:/usr/share/nginx/html/fmtm/
      - certs:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    environment:
      FMTM_DOMAIN: ${FMTM_DOMAIN}
      FMTM_API_DOMAIN: ${FMTM_API_DOMAIN:-api.${FMTM_DOMAIN}}
      FMTM_SCRIPT_DOMAIN: ${FMTM_SCRIPT_DOMAIN:-_}
    ports:
      - 80:80
      - 443:443
    networks:
      - fmtm-net
    restart: "unless-stopped"

  api:
    image: "ghcr.io/hotosm/fmtm/backend:main"
    container_name: fmtm-api-main
    volumes:
      - fmtm_logs:/opt/logs
      - fmtm_tiles:/opt/tiles
    depends_on:
      fmtm-db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    networks:
      - fmtm-net
    restart: "unless-stopped"

  ui:
    # This service simply builds the frontend to a volume
    # accessible to the proxy, then shuts down
    image: "ghcr.io/hotosm/fmtm/frontend:${GIT_BRANCH:-main}"
    build:
      context: src/frontend
      dockerfile: prod.dockerfile
      args:
        APP_VERSION: main
        VITE_API_URL: https://${FMTM_API_DOMAIN:-api.${FMTM_DOMAIN}}
    container_name: fmtm-ui-main
    volumes:
      - fmtm_frontend:/frontend
    network_mode: none
    restart: "on-failure:2"

  fmtm-db:
    image: "postgis/postgis:${POSTGIS_TAG:-14-3.4-alpine}"
    container_name: fmtm-db-main
    volumes:
      - fmtm_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${FMTM_DB_USER}
      - POSTGRES_PASSWORD=${FMTM_DB_PASSWORD}
      - POSTGRES_DB=${FMTM_DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - fmtm-net
    restart: "unless-stopped"
    healthcheck:
      test: pg_isready -U ${FMTM_DB_USER} -d ${FMTM_DB_NAME}
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  migrations:
    image: "ghcr.io/hotosm/fmtm/backend:main"
    container_name: fmtm-migrations-main
    depends_on:
      fmtm-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - fmtm-net
    entrypoint: ["/migrate-entrypoint.sh"]
    restart: "on-failure:3"

  backups:
    image: "ghcr.io/hotosm/fmtm/backend:main"
    container_name: fmtm-backups-main
    depends_on:
      fmtm-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - fmtm-net
    entrypoint: ["/backup-entrypoint.sh"]
    restart: "on-failure:3"
    healthcheck:
      test: pg_isready -U ${FMTM_DB_USER} -d ${FMTM_DB_NAME}
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  certbot:
    image: "ghcr.io/hotosm/fmtm/proxy:certs-init-main"
    container_name: fmtm-cert-renew-main
    volumes:
      - certs:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    environment:
      FMTM_DOMAIN: ${FMTM_DOMAIN}
      FMTM_API_DOMAIN: ${FMTM_API_DOMAIN:-api.${FMTM_DOMAIN}}
      FMTM_SCRIPT_DOMAIN: ${FMTM_SCRIPT_DOMAIN:-_}
      CERT_EMAIL: ${CERT_EMAIL}
    ports:
      - 80:80
      - 443:443
    networks:
      - fmtm-net
    restart: "on-failure:2"
