name: 🔧 Build ODK Images

on:
  # Push includes PR merge
  push:
    branches:
      - development
    paths:
      # Workflow is triggered only if odkcentral dir changes
      - "odkcentral/**"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-odkcentral:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.4.0
    with:
      context: odkcentral/api
      image_tags: |
        "ghcr.io/${{ github.repository }}/odkcentral:${{ vars.ODK_CENTRAL_TAG }}"
        "ghcr.io/${{ github.repository }}/odkcentral:latest"
      extra_build_args: |
        ODK_CENTRAL_TAG=${{ vars.ODK_CENTRAL_TAG }}
      # odkcentral backend npm install fails on ARM64
      # uncomment once fixed
      # multi_arch: true

  build-odkcentral-ui:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.4.0
    with:
      context: odkcentral/ui
      image_tags: |
        "ghcr.io/${{ github.repository }}/odkcentral-ui:${{ vars.ODK_CENTRAL_TAG }}"
        "ghcr.io/${{ github.repository }}/odkcentral-ui:latest"
      extra_build_args: |
        ODK_CENTRAL_TAG=${{ vars.ODK_CENTRAL_TAG }}
      multi_arch: true
