name: 🔧 Build Proxy Images

on:
  # Trigger on schedule
  schedule:
    # Run 2:00 on 1st and 15th of every month
    - cron: "0 2 1,15 * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-cert-init-main:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.3.1
    with:
      context: nginx
      build_target: certs-init-main
      image_tags: |
        "ghcr.io/${{ github.repository }}/proxy:certs-init-main"
      extra_build_args: |
        NGINX_TAG=${{ vars.NGINX_TAG }}

  build-cert-init-dev:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.3.1
    with:
      context: nginx
      build_target: certs-init-development
      image_tags: |
        "ghcr.io/${{ github.repository }}/proxy:certs-init-development"
        "ghcr.io/${{ github.repository }}/proxy:certs-init-staging"
      extra_build_args: |
        NGINX_TAG=${{ vars.NGINX_TAG }}

  build-proxy-main:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.3.1
    with:
      context: nginx
      build_target: main
      image_tags: |
        "ghcr.io/${{ github.repository }}/proxy:main"
      extra_build_args: |
        NGINX_TAG=${{ vars.NGINX_TAG }}

  build-proxy-main-plus-script:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.3.1
    with:
      context: nginx
      build_target: main-plus-script
      image_tags: |
        "ghcr.io/${{ github.repository }}/proxy:main-plus-script"
      extra_build_args: |
        NGINX_TAG=${{ vars.NGINX_TAG }}

  build-proxy-dev:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.3.1
    with:
      context: nginx
      build_target: development
      image_tags: |
        "ghcr.io/${{ github.repository }}/proxy:development"
        "ghcr.io/${{ github.repository }}/proxy:staging"
      extra_build_args: |
        NGINX_TAG=${{ vars.NGINX_TAG }}
