name: 📖 Publish Docs to Wiki

on:
  push:
    paths:
      - docs/**
    branches: [development]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  publish-docs-to-wiki:
    uses: hotosm/gh-workflows/.github/workflows/wiki.yml@1.3.1
    with:
      homepage_path: "wiki_redirect.md"
